### ISSUE TITLE
Bloatcrawl2 2.2.0 webtiles game crashes immediately

### ISSUE THREAD

**Issue by Djent-** [Hellmonk/bloatcrawl2#59]
Starting Bloatcrawl2 2.2.0 webtiles game crashes immediately. Error occurs when clicking the Play Now link

**PLATFORM and OS or BROWSER:**
Webtiles on Raspbian ARM

**DCSS VERSION:**
2.2.0

**DESCRIPTION:**
```
2020-03-26 12:56:50,874 ERROR: #1     P1     Error while handling lockfile ./rcs/running/djent:2020-03-26.04:33:21.ttyrec.
Traceback (most recent call last):
  File "/home/pi/build/crawl-server/2.2.0/source/webserver/process_handler.py", line 585, in _purge_locks_and_start
    pid = int(pid)
ValueError: invalid literal for int() with base 10: ''
```

**EXTRA FILES:**
N/A

**Comment by alexjurkiewicz** [comment]
That's an issue with the webtiles code. Use the webtiles server from vanilla

**Comment by Djent-** [comment]
Are you talking about the contents of the source/webserver folder?
I have tested it by adding the bloatcrawl paths to the vanilla webserver/config.py, and the same error occurs. This is specific to bloatcrawl

Also note that the markdown gobbled the first line of the error message when I pasted it:

```
2020-03-26 12:56:50,874 ERROR: #1     P1     Error while handling lockfile ./rcs/running/djent:2020-03-26.04:33:21.ttyrec.
Traceback (most recent call last):
  File "/home/pi/build/crawl-server/2.2.0/source/webserver/process_handler.py", line 585, in _purge_locks_and_start
    pid = int(pid)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by alexjurkiewicz** [comment]
The error is from code related to the webtiles server game start logic
related to parsing a pid file. I don't think it's related to bloatcrawl,
unless it's something unusual bloatcrawl is doing like crashing in a way
the webtiles server can't handle.

**Comment by Djent-** [comment]
I think that my issue with starting bloatcrawl with the bloatcrawl webserver is a different issue than the issue I have starting bloatcrawl with the vanilla trunk webserver. I was able to solve the latter by manually creating a directory for my user under /rcs/ttyrecs/. This is because the error was slightly different (albeit in the same region of code):

```
2020-03-27 23:37:37,036 WARN: #0     P3     Error while starting the Crawl process!
Traceback (most recent call last):
  File "/home/pi/build/crawl-server/trunk/source/webserver/process_handler.py", line 740, in _start_process
    config.recording_term_size)
  File "/home/pi/build/crawl-server/trunk/source/webserver/terminal.py", line 20, in __init__
    self.ttyrec = open(filename, "wb", 0)
IOError: [Errno 2] No such file or directory: u'/home/pi/build/crawl-server/2.2.0/source/rcs/ttyrecs/djent/2020-03-28.03:37:37.ttyrec'
2020-03-27 23:37:37,040 INFO: #0     P3     Crawl terminated.
```

I suspect (cannot confirm) that the issue with bloatcrawl + bloatcrawl webserver is that on my Raspberry Pi, bloatcrawl takes too long to start, and the webserver cannot write the pid in time to be read.

**Comment by alexjurkiewicz** [comment]
Every official server running bloatcrawl is using the standard vanilla
server, so that's what I'd recommend you keep using. You can try adding a
sleep around the spot, if you think slow startup is to blame :\
